### ISSUE TITLE
Wont run

### ISSUE THREAD

**Issue by legramps** [EnervationRIN/RimworldModUpdater#1]
I tried to run the exe however it doesnt popup and theres no error indicator.  Windows 10 20H1 (fresh install)
It was running on a previous windows 10 version and before i changed the motherboard.

**Comment by EnervationRIN** [comment]
Please include your log.txt and make sure you have .net 4.7.2 installed
https://dotnet.microsoft.com/download/dotnet-framework/net472

**Comment by legramps** [comment]
theres no log.txt in the folder of the mod updater and i cant even install it since `.NET Framework 4.7.2 or a later update is already installed on this computer.
` i have 4.8

**Comment by EnervationRIN** [comment]
Since you're using a fresh copy of windows, try to install the visual C++ redists.
https://github.com/abbodi1406/vcredist/releases/tag/v0.34.0

**Comment by legramps** [comment]
Thank you so much it worked!
